### User 2 (testing app)
@tokenUser2 = b0506867-77c3-4142-9437-1f627deebd67

### Insert a Group
POST http://localhost:8000/groups HTTP/2
Content-Type: application/json
Authorization: Bearer {{tokenUser2}}

{
    "name": "PT Group",
    "description": "Best Portuguese League players",
    "competition": {
        "code": "PT",
        "name": "Liga Portugal"
    },
    "year": 2024
}

### Delete group pt group
DELETE http://localhost:8000/groups/PT%20Group HTTP/2
Authorization: Bearer {{tokenUser2}}

### Insert a Group

POST http://localhost:8000/groups HTTP/2
Content-Type: application/json
Authorization: Bearer {{tokenUser2}}

{
    "name": "PL Group",
    "description": "Best Premier League players",
    "competition": {
        "code": "PL",
        "name": "Premier League"
    },
    "year": 2024
}

### Get all groups

GET http://localhost:8000/groups HTTP/2
Authorization: Bearer {{tokenUser2}}

### Insert a Group

POST http://localhost:8000/groups HTTP/2
Content-Type: application/json
Authorization: Bearer {{tokenUser2}}

{
    "name": "test1",
    "description": "Test Query",
    "competition": {
        "code": "PL",
        "name": "Premier League"
    },
    "year": 2024
}

### Insert a Group

POST http://localhost:8000/groups HTTP/2
Content-Type: application/json
Authorization: Bearer {{tokenUser2}}

{
    "name": "test2",
    "description": "Test Query",
    "competition": {
        "code": "PL",
        "name": "Premier League"
    },
    "year": 2024
}

### Get groups with search
GET http://localhost:8000/groups?search=Test+Query
Authorization: Bearer {{tokenUser2}}

### Get group PT_GROUP

GET http://localhost:8000/groups/PT%20Group HTTP/2
Authorization: Bearer {{tokenUser2}}

### Update group PT_GROUP
PUT http://localhost:8000/groups/PT%20Group HTTP/2
Content-Type: application/json
Authorization: Bearer {{tokenUser2}}

{
    "name": "group1",
    "description": "rename group PT_GROUP to group1"
}

### Get group group1

GET http://localhost:8000/groups/group1 HTTP/2
Authorization: Bearer {{tokenUser2}}

### Delete group group1

DELETE http://localhost:8000/groups/group1 HTTP/2
Authorization: Bearer {{tokenUser2}}

### Add player to group
POST http://localhost:8000/groups/PL%20Group/players/123
Content-Type: application/json
Authorization: Bearer {{tokenUser2}}

{
  "playerId": "123",
  "playerName": "Guilherme",
  "teamCode": "SLB",
  "teamName": "Benfica"
}

### Get group PL_GROUP

GET http://localhost:8000/groups/PL%20Group HTTP/2
Authorization: Bearer {{tokenUser2}}

### Remove player from group
DELETE http://localhost:8000/groups/PL%20Group/players/123
Authorization: Bearer {{tokenUser2}}

### Get group PL_GROUP
GET http://localhost:8000/groups/PL%20Group HTTP/2
Authorization: Bearer {{tokenUser2}}

### ADD 12 PLAYERS TO A GROUP AND SEE WHAT HAPPENS
### 1/12 Add Player
POST http://localhost:8000/groups/PL%20Group/players/1
Authorization: Bearer {{tokenUser2}}

### 2/12 Add Player
POST http://localhost:8000/groups/PL%20Group/players/2
Authorization: Bearer {{tokenUser2}}

### 3/12 Add Player
POST http://localhost:8000/groups/PL%20Group/players/3
Authorization: Bearer {{tokenUser2}}

### 4/12 Add Player
POST http://localhost:8000/groups/PL%20Group/players/4
Authorization: Bearer {{tokenUser2}}

### 5/12 Add Player
POST http://localhost:8000/groups/PL%20Group/players/5
Authorization: Bearer {{tokenUser2}}

### 6/12 Add Player
POST http://localhost:8000/groups/PL%20Group/players/6
Authorization: Bearer {{tokenUser2}}

### 7/12 Add Player
POST http://localhost:8000/groups/PL%20Group/players/7
Authorization: Bearer {{tokenUser2}}

### 8/12 Add Player
POST http://localhost:8000/groups/PL%20Group/players/8
Authorization: Bearer {{tokenUser2}}

### 9/12 Add Player
POST http://localhost:8000/groups/PL%20Group/players/9
Authorization: Bearer {{tokenUser2}}

### 10/12 Add Player
POST http://localhost:8000/groups/PL%20Group/players/10
Authorization: Bearer {{tokenUser2}}

### 11/12 Add Player
POST http://localhost:8000/groups/PL%20Group/players/11
Authorization: Bearer {{tokenUser2}}

### 12/12 Add Player
### ERRO AO ADICIONAR
POST http://localhost:8000/groups/PL%20Group/players/12
Authorization: Bearer {{tokenUser2}}

### Get competitions

GET http://localhost:8000/competitions HTTP/2
Authorization: Bearer {{tokenUser2}}

### Get teams

GET http://localhost:8000/competitions/PPL/season/2023/teams HTTP/2
Authorization: Bearer {{tokenUser2}}
